[book]
authors = ["Sagi"]
title = "The LearnixOS Book"
language = "en"

[output.html]
default-theme = "rust"
preferred-dark-theme = "mocha"
additional-css = ["theme/catppuccin.css"]

[output.linkcheck]
follow-web-links = true
traverse-parent-directories = false
