name: spellcheck

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action Repository
        uses: actions/checkout@v4

      - name: Check the Spelling of the Book
        uses: crate-ci/typos@1.34.0
