name: spellcheck

on:
  workflow_run:
    workflows: ["linkcheck"]
    types:
      - completed
jobs:
  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action Repository
        uses: actions/checkout@v4

      - name: Check the Spelling of the Book
        uses: crate-ci/typos@v1.34.0
