name: validate

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:


jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook,mdbook-linkcheck

      - name: Run link checker
        run: mdbook build

  spellcheck:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action Repository
        uses: actions/checkout@v4

      - name: Check the Spelling of the Book
        uses: crate-ci/typos@v1.34.0

